name: Waka Readme

on:
  schedule:
    # Executa à meia-noite (UTC) todos os dias
    - cron: "0 0 * * *"
  workflow_dispatch:
    # Permite que você execute a ação manualmente pela aba Actions

jobs:
  update-readme:
    name: Update Readme with Waka Stats
    runs-on: ubuntu-latest
    steps:
      - uses: anuraghazra/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIMEKEY }}
